
version: 2

models:
  - name: transactions__preprocessing
    description: "A starter dbt_project1 model"
    columns:
      - name: tx_id
        description: "The transaction id"
        tests:
          - not_null
      - name: customer_id
        description: "The customer id"
        tests:
          - unique
      - name: terminal_id
        description: "The terminal id"
        tests:
          - unique

